name: commit-status-action
description: Update commit status according to job results
inputs:
  repo_owner:
    description: Repository Owner
    required: false
  repo_name:
    description: Repository Name
    required: false
  sha:
    description: Commit hash
    required: false
  github_token:
    description: GitHub Access Token
    required: false
  target_url:
    description: target URL
    required: false
  state:
    description: A string label to differentiate this status from the status of other systems. This field is case-insensitive
    required: false
    default: pending
  context:
    description: A string label to differentiate this status from the status of other systems. This field is case-insensitive
    required: false
  needs:
    description: needs context.
    required: false
  start_workflow:
    description: Set true if you update the commit status per workflow and you want to update the commit status in this step. You should set true in only one step.
    required: false
    default: false
runs:
  using: node16
  main: dist/index.js
